
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
    "docs": [
        "intro",
        {
            "type": "category",
            "label": "Getting started",
            "items": [
                "outline-file",
                "install-skelosaurus",
                "build-documentation-skeleton"
            ]
        },
        "build-documentation-skeleton",
        {
            "type": "category",
            "label": "YAML Outline",
            "items": [
                "yaml-outline-schema",
                "examples-of-yaml-outline"
            ]
        },
        "api",
        {
            "type": "category",
            "label": "Guides",
            "items": [
                "skelosaurus-and-docusaurus-together",
                "prepare-and-develop-documention-outline"
            ]
        }
    ],
    "tutorials": [
        "tutorials/index",
        "tutorials/outline-file-with-several-sidebars",
        "tutorials/detailed-vs-shortend-element-description"
    ]
}
/*
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};
*/

module.exports = sidebars;
